### ISSUE TITLE
你好，微信版本更新后CMenuWnd窗口具柄获取不到了，想问下代码click_menu_wnd这块逻辑用处

### ISSUE THREAD

**Issue by HelloZZZC** [xzkzdx/weixin-spider#10]

**Comment by HelloZZZC** [comment]
之前没有接触过window桌面应用都编程

**Comment by buleZia** [comment]
@HelloZZZC 请问该问题解决了吗？我debug的过程中也遇到同样的问题了
# click_menu_wnd()是为了调出右键菜单把链接粘贴在聊天窗口里发送，是为了后面打开文章链接获取文章内容使用的

**Comment by HelloZZZC** [comment]
你好，我的方式比较粗暴。。我自己查了一下代码中FindWindow是从顶层窗口中获取CMenuWnd的句柄，然后我通过win32api.SetCursorPos()，cmenuwnd = win32gui.WindowFromPoint(win32api.GetCursorPos())、win32gui.GetClassName(cmenuwnd)确实是能获取到的。因此我怀疑是不是微信改动了结构导致。所以我就干脆将鼠标固定在传输助手窗口的聊天窗口，然后去单机鼠标粘贴。代码是下面这样的
cursor_hight = self.rect[3] - 50
cursor_width = int((self.rect[0] + self.rect[2])/2)
win32api.SetCursorPos((cursor_width, cursor_hight))
self.handle_model.mouse_right_click_position(self.handle, rect_position)
time.sleep(0.001)
win32api.SetCursorPos((cursor_width + 5, cursor_hight + 5))
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP | win32con.MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)


time.sleep(0.001)
self.handle_model.mouse_left_click_position(self.handle, (self.handle_size[0] - 60, self.handle_size[1] - 15))
time.sleep(0.1)



还不清楚对整体的影响，只是暂时先这么用着。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"buleZia"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午2:21
收件人:&nbsp;"xzkzdx/weixin-spider"<weixin-spider@noreply.github.com&gt;;
抄送:&nbsp;"Mr.zzzzc"<405954049@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xzkzdx/weixin-spider] 你好，微信版本更新后CMenuWnd窗口具柄获取不到了，想问下代码click_menu_wnd这块逻辑用处 (#10)





 
@HelloZZZC 请问该问题解决了吗？我debug的过程中也遇到同样的问题了
 
click_menu_wnd()是为了调出右键菜单把链接粘贴在聊天窗口里发送，是为了后面打开文章链接获取文章内容使用的

**Comment by buleZia** [comment]
@HelloZZZC 感谢回复，我的解决方式和你的差不多，用ctrl+v直接粘贴了
```
def send_msg(self, msg: str):
    self.handle_model.text_to_clipboard(msg)
    rect_position = (200, self.handle_size[1] - 50)
    self.handle_model.mouse_left_click_position(self.handle, rect_position)
    time.sleep(0.001)
    for key in [17, 86]: win32api.keybd_event(key, 0, 0, 0)
    for key in [17, 86]: win32api.keybd_event(key, 0, win32con.KEYEVENTF_KEYUP, 0)
    time.sleep(0.5)
    self.handle_model.mouse_left_click_position(self.handle, (self.handle_size[0] - 60, self.handle_size[1] - 15))
    time.sleep(0.1)
```
