### ISSUE TITLE
大佬，监控时显示CMENUWIND窗口不存在，求教

### ISSUE THREAD

**Issue by feiyangdezhu** [xzkzdx/weixin-spider#15]
大佬，监控时显示CMENUWIND窗口不存在，求教

**Comment by xzkzdx** [comment]
登录微信PC版后，找到 文件传输助手 对话框， 双击 文件传输助手 ，文件传输助手会自动弹出单独的对话窗口来

**Comment by feiyangdezhu** [comment]
大佬，之前也是按您的操作来的，但是还是显示CMENUWIND窗口不存在
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xzkzdx/weixin-spider"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 下午5:20
收件人:&nbsp;"xzkzdx/weixin-spider"<weixin-spider@noreply.github.com&gt;;
抄送:&nbsp;"2543643450"<2543643450@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xzkzdx/weixin-spider] 大佬，监控时显示CMENUWIND窗口不存在，求教 (#15)





 
登录微信PC版后，找到 文件传输助手 对话框， 双击 文件传输助手 ，文件传输助手会自动弹出单独的对话窗口来

**Comment by xzkzdx** [comment]
更新，

**Comment by feiyangdezhu** [comment]
更新什么啊？我是按照所有流程来的啊，不知道问题出在哪里了。
